# --- !Ups

SET IGNORECASE TRUE;

CREATE TABLE USER (
  ID IDENTITY NOT NULL,
  NAME VARCHAR_IGNORECASE(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FULL_NAME VARCHAR(255),
  EMAIL VARCHAR_IGNORECASE(255),
  IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,

  PRIMARY KEY (ID)
);

CREATE TABLE POST (
  ID IDENTITY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  CONTENT VARCHAR(255),
  POSTED_AT DATE,
  AUTHOR_ID BIGINT,

  FOREIGN KEY (AUTHOR_ID) REFERENCES USER(ID),
  PRIMARY KEY (ID)
);


# --- !Downs

DROP TABLE USER IF EXISTS;

DROP TABLE POST IF EXISTS;